# Generated by Django 3.2.4 on 2021-10-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LacasaLiqour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('name', models.CharField(max_length=20)),
                ('qty', models.PositiveIntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
