# Generated by Django 3.2.4 on 2021-11-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.OneToOneField(help_text='name', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(auto_created=True)),
                ('date_order', models.DateField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LaCasaDelLiqour.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-image')),
                ('name', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('Vodka', 'Vodka'), ('Whiskey', 'Whiskey'), ('Wine', 'Wine'), ('Gin', 'Gin'), ('Beer', 'Beer'), ('Rum', 'Rum')], max_length=8, null=True)),
                ('size', models.CharField(choices=[('250ml', '250ml'), ('500ml', '500ml'), ('750ml', '750ml'), ('1L', '1L')], max_length=5, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(help_text='07********')),
                ('county', models.CharField(help_text='your county', max_length=30)),
                ('town', models.CharField(help_text='nearest shopping centre or town', max_length=50)),
                ('pick_point', models.CharField(help_text='exact point of colleection', max_length=70)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LaCasaDelLiqour.products')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LaCasaDelLiqour.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LaCasaDelLiqour.products')),
            ],
        ),
    ]
