# Generated by Django 3.2.4 on 2021-11-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
