# Generated by Django 3.2.4 on 2021-10-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lacasaliqour',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lacasaliqour',
            name='qty',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
