# Generated by Django 3.2.4 on 2021-10-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0002_auto_20211008_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lacasaliqour',
            name='qty',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
