# Generated by Django 3.2.4 on 2021-11-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0002_alter_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
