# Generated by Django 3.2.4 on 2021-11-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0003_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='qty',
            new_name='quantity',
        ),
    ]
