# Generated by Django 3.2.4 on 2021-10-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0004_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_no',
            field=models.PositiveIntegerField(help_text='07********'),
        ),
    ]
