# Generated by Django 3.2.4 on 2021-11-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0004_rename_qty_products_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qty',
            new_name='quantity',
        ),
    ]
