# Generated by Django 3.2.4 on 2021-11-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0005_rename_qty_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='img',
            new_name='image',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Vodka', 'Vodka'), ('Whiskey', 'Whiskey'), ('Wine', 'Wine'), ('Gin', 'Gin'), ('Beer', 'Beer'), ('Rum', 'Rum')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('250ml', '250ml'), ('500ml', '500ml'), ('750ml', '750ml'), ('1L', '1L')], max_length=5, null=True),
        ),
    ]
