# Generated by Django 3.2.4 on 2021-10-13 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0006_auto_20211010_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LacasaLiqour',
            new_name='Products',
        ),
    ]
