# Generated by Django 3.2.4 on 2021-11-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LaCasaDelLiqour', '0006_auto_20211115_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone_no',
            field=models.IntegerField(help_text='07********'),
        ),
    ]
